name: dail_bites
description: "The next big ecommerce app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  pocketbase: ^0.18.1
  flutter_staggered_grid_view:
  cached_network_image: 
  bloc: ^8.1.4
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  lottie: ^3.1.3
  url_launcher: ^6.3.1
  toastification: ^2.3.0
  flutter_paystack_plus: 2.1.0
  intl:
  google_fonts: ^6.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
  
